title: "Mhaykol Eng — Cyber Threat Intelligence"
description: "Briefings CTI, writeups reproducibles y proyectos aplicados. Threat-led analysis para SOC y dirección."
url: "https://sparkhacky.github.io"
baseurl: "" # no subpath para user/organization site

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Madrid

# Plugins permitidos por GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Navegación (usa page.url == item.link)
nav:
  - title: Inicio
    link: /
  - title: Briefings
    link: /blog/
  - title: Writeups
    link: /writeups/
  - title: Proyectos
    link: /projects/
  - title: About
    link: /about/

# Colecciones
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults (layouts/metadata)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: blog
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: writeup
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

# SEO
social:
  links:
    - https://www.linkedin.com/in/tu-perfil
    - https://x.com/tu_usuario
    - https://youtube.com/@tu_canal

# Feed
feed:
  path: feed.xml
