title: "Sparkhacky - Portfolio"
description: "Briefings CTI, writeups reproducibles y proyectos aplicados. Threat-led analysis para SOC y dirección."
url: "https://sparkhacky.github.io"
baseurl: ""

# _config.yml
hero_image: /assets/images/hero.jpg
hero_image_fallback: /assets/images/hero.jpg


markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: Europe/Madrid

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

nav:
  - title: Inicio
    link: /
  - title: Briefings
    link: /blog/
  - title: Writeups
    link: /writeups/
  - title: Proyectos
    link: /projects/
  - title: About
    link: /about/

collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      category: blog
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: writeup
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

social:
  links:
    - https://www.linkedin.com/in/tu-perfil
    - https://x.com/tu_usuario
    - https://youtube.com/@tu_canal

feed:
  path: feed.xml
