title: "SparkHacky INTEL"
description: "Portfolio — Writeups, Proyectos y Blog de Ciberinteligencia"
url: "https://sparkhacky.github.io"   # sin barra final
baseurl: ""                           # user/ORG page => vacío

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Salidas y rutas limpias
permalink: /:categories/:title/

collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: post }
  - scope: { path: "", type: "writeups" }
    values: { layout: writeup }
  - scope: { path: "", type: "projects" }
    values: { layout: project }

# Navegación
nav:
  - { name: "Inicio",   link: "/" }
  - { name: "Blog",     link: "/blog/" }
  - { name: "Writeups", link: "/writeups/" }
  - { name: "Proyectos",link: "/projects/" }
  - { name: "About",    link: "/about/" }

author:
  name: "Mhaykol Eng"
  email: "tu-email@proton.me"
